spring:
  application:
    name: assessment-service

  data:
    mongodb:
      uri: mongodb://root:pass@mongodb:27017/assessmentdb?authSource=admin

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 8084

logging:
  level:
    org.springframework.data.mongodb: INFO
    com.example.notesservice: DEBUG