spring:
  application:
    name: patient-service

  datasource:
    url: jdbc:mysql://localhost:3306/patientdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082

logging:
  level:
    com.example.medilabo: DEBUG
