spring:
  application:
    name: notes-service

  data:
    mongodb:
      uri: mongodb://root:pass@mongodb:27017/notesdb?authSource=admin

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 8083

logging:
  level:
    org.springframework.data.mongodb: INFO
    com.example.notesservice: DEBUG
